line-length = 88
indent-width = 4

exclude = [
    ".git",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    "coverage",
    "assets",
    "docs",
    "frameworks/claude-code/dist",
]

[lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "UP", # pyupgrade
    "C4", # flake8-comprehensions
    "SIM" # flake8-simplify
]
ignore = [
    "E203", # whitespace before ':' (black-compatible)
    "W503", # line break before binary operator (black-compatible)
]

[lint.isort]
known-first-party = ["agents", "tools", "templates", "projects", "utils"]

